baseURL = "https://adrinaminsalehi.com/"
languageCode = "en-us"
title = "Adrin Amin Salehi"
paginate = 5

###########################################
# This part is for Hugo modules for content

[module]
[[module.imports]]
    path = "github.com/adrinamin/articles_and_notes"
    disabled = false
[[module.imports.mounts]]
    source = "."
    target = "content"

###########################################