name: Deploy to Firebase Hosting on merge

on:
  push:
    branches: [ master, main ]

jobs:
  build_and_deploy:
    name: build and deploy
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'
    
    - name: build source code      
      run: hugo --minify
      working-directory: source/

    - name: setup firebase and deploy
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ADRINAMINSALEHI_WEBSITE }}'
        token: '${{ secrets.WORKFLOW_TOKEN }}'
        channelId: live
        projectId: adrinaminsalehi-website
      env:
        FIREBASE_CLI_PREVIEWS: hostingchannels
